export const listRows = [
  {
    id: 'l1',
    name: 'Technology, Transactions, and Privacy Law',
    owner: 'Chad Cinco',
    members: 27,
    lastEngagement: '3 days ago',
    tag: 'Privacy & Security',
    initials: 'T',
    color: 'cyan',
  },
  {
    id: 'l2',
    name: 'Mergers & Acquisitions Insiders',
    owner: 'Cindy Luhu',
    members: 139,
    lastEngagement: '1 day ago',
    tag: 'Mergers & Acquisitions',
    initials: 'M',
    color: 'yellow',
  },
  {
    id: 'l3',
    name: 'Regulatory Affairs Network Dinner',
    owner: 'Oji Saka',
    members: 15,
    lastEngagement: '14 days ago',
    tag: 'Event',
    initials: 'R',
    color: 'purple',
  },
  {
    id: 'l4',
    name: 'Annual Golf Event 2025',
    owner: 'Billy Maisear',
    members: 27,
    lastEngagement: '46 days ago',
    tag: 'Event',
    initials: 'G',
    color: 'green',
  },
];
